### ISSUE TITLE
MSP432 UniFlash 3.4.1 Compatibility 

### ISSUE THREAD

**Issue by rei-vilo** [robertinant/EnergiaNG#2]
The latest release of UniFlash 3.4.1 updated the firmware for the MSP430F5529 and MSP432.

Does Energia plan to share the same release of the firmwares?

**Comment by rei-vilo** [comment]
No more **Tools > Update Programmer** menu — See #3

**Comment by robertinant** [comment]
I just updated DSLite to version 6.2.1.1624 and that should match what is in uniflash. Also, all OS'es should not have the same firmware included for all emulators so no more upgrading/downgrading when you move your board from on OS to the other. Unfortunately tools can not be updated separate from the cores and the the core package dependent on it has to change revision for the change to take effect. I will do this starting with MSP432 that will be updated later today and then soon after for the other core packages.
