### ISSUE TITLE
Missing Tools > Update Programmer Menu

### ISSUE THREAD

**Issue by rei-vilo** [robertinant/EnergiaNG#3]
The menu **Tools > Update Programmer** is no longer available.

**Comment by robertinant** [comment]
Tools->Update Programmer is no longer applicable since DSLite now updates the programmer automatically when needed if you upload your Sketch.

**Comment by rei-vilo** [comment]
DSLite performed fine for the MSP432 but failed to update the firmware for the MSP430F5529. I had to use Energia 17 and upload the firmware again.
