### ISSUE TITLE
robertinant/EnergiaNG Temporary Repository?

### ISSUE THREAD

**Issue by rei-vilo** [robertinant/EnergiaNG#4]
Is the [robertinant/EnergiaNG](https://github.com/robertinant/EnergiaNG) repository temporary before being moved at [Energia/Energia](https://github.com/energia/Energia)?

**Comment by robertinant** [comment]
Yes, it is temporarily under my github account and will be moved to Energia. The reason why it is there is that github does not allow 2 repo's that have the same upstream tracking in this case Arduino/arduino.
