### ISSUE TITLE
Splash Screen Still with 17 Release

### ISSUE THREAD

**Issue by rei-vilo** [robertinant/EnergiaNG#6]
<img width="477" alt="capture 2016-06-29 a 13 38 52" src="https://cloud.githubusercontent.com/assets/951776/16450717/e451cf58-3dfe-11e6-8aef-f053009eb304.png">

**Comment by RickKimball** [comment]
Also a problem on linux

**Comment by rei-vilo** [comment]
Suggestion...

![energia mt updated splash screen](https://cloud.githubusercontent.com/assets/951776/16460790/748c8f16-3e29-11e6-8f1e-a81181f7f7c1.jpeg)

**Comment by robertinant** [comment]
Yes, the version number is displayed in both the title bar as well as in the top left corner of the splash screen. Both of these are generated from the version numbers in the IDE. So no need for an explicit version number and going to remove. In fact, if you can send me that splash screen in the right size then I'll use that.
