### ISSUE TITLE
Help menu items broken

### ISSUE THREAD

**Issue by RickKimball** [robertinant/EnergiaNG#9]
Selecting any of the help menu items shows a dialog box:

"Problem Opening URL"
/mnt/vbox/shared/Downloads/energia-1.6.10E18B6//reference/www.energia.nu/Guide_Linux.html

If you try other help menu items they produce a similar message

The only menu items that work are "About" and "Visit energia.nu"

On linux btw

**Comment by robertinant** [comment]
This was an issue with the unzip target on linux. The rule specifies -n to never overwrite existing files in the directory "www.energia.nu". The directory "www.energia.nu" already existed and for some reason was empty. This probably triggered unzip to not extract the files.
This is a release build issue. I now have a script in place that does a clean before a dist and thus will solve the issue.
